[tool.poetry]
name = "hw_poetry_docker"
version = "0.1.0"
description = ""
authors = ["pavlo-boichuk <betonsuccess@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
